# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The layout of this form has two columns:
columns:
  - width: 1/2
    sections:
      schedule: sections/schedule

  # The second column has two sections, `notes` and `pages`
  - width: 1/2
    sections:
      # The `notes` section reuses the pages section defined in `/site/blueprints/sections/notes.yml`
      news: sections/news
      series: sections/series
      pages:
        type: pages
        create: default

